package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADVERTS.
 */
public class Adverts {

    private Long id;
    private String advert_pic;
    private String advert_name;
    private String advert_url;

    public Adverts() {
    }

    public Adverts(Long id) {
        this.id = id;
    }

    public Adverts(Long id, String advert_pic, String advert_name, String advert_url) {
        this.id = id;
        this.advert_pic = advert_pic;
        this.advert_name = advert_name;
        this.advert_url = advert_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAdvert_pic() {
        return advert_pic;
    }

    public void setAdvert_pic(String advert_pic) {
        this.advert_pic = advert_pic;
    }

    public String getAdvert_name() {
        return advert_name;
    }

    public void setAdvert_name(String advert_name) {
        this.advert_name = advert_name;
    }

    public String getAdvert_url() {
        return advert_url;
    }

    public void setAdvert_url(String advert_url) {
        this.advert_url = advert_url;
    }

}
