package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISTRIBUTION.
 */
public class Distribution {

    private Long id;
    private String name;
    private String introuduction;
    private String location;
    private String scale;
    private String webSite;
    private String telePhone;
    private String address;

    public Distribution() {
    }

    public Distribution(Long id) {
        this.id = id;
    }

    public Distribution(Long id, String name, String introuduction, String location, String scale, String webSite, String telePhone, String address) {
        this.id = id;
        this.name = name;
        this.introuduction = introuduction;
        this.location = location;
        this.scale = scale;
        this.webSite = webSite;
        this.telePhone = telePhone;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIntrouduction() {
        return introuduction;
    }

    public void setIntrouduction(String introuduction) {
        this.introuduction = introuduction;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getScale() {
        return scale;
    }

    public void setScale(String scale) {
        this.scale = scale;
    }

    public String getWebSite() {
        return webSite;
    }

    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    public String getTelePhone() {
        return telePhone;
    }

    public void setTelePhone(String telePhone) {
        this.telePhone = telePhone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

}
