package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GAME_TYPE.
 */
public class GameType {

    private Long id;
    private String title;
    private String advert_cat_id;

    public GameType() {
    }

    public GameType(Long id) {
        this.id = id;
    }

    public GameType(Long id, String title, String advert_cat_id) {
        this.id = id;
        this.title = title;
        this.advert_cat_id = advert_cat_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAdvert_cat_id() {
        return advert_cat_id;
    }

    public void setAdvert_cat_id(String advert_cat_id) {
        this.advert_cat_id = advert_cat_id;
    }

}
