package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INDEX_ADVERT.
 */
public class IndexAdvert {

    private Long id;
    private String user_id;
    private String advert_pic;
    private String advert_name;
    private String advert_url;

    public IndexAdvert() {
    }

    public IndexAdvert(Long id) {
        this.id = id;
    }

    public IndexAdvert(Long id, String user_id, String advert_pic, String advert_name, String advert_url) {
        this.id = id;
        this.user_id = user_id;
        this.advert_pic = advert_pic;
        this.advert_name = advert_name;
        this.advert_url = advert_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getAdvert_pic() {
        return advert_pic;
    }

    public void setAdvert_pic(String advert_pic) {
        this.advert_pic = advert_pic;
    }

    public String getAdvert_name() {
        return advert_name;
    }

    public void setAdvert_name(String advert_name) {
        this.advert_name = advert_name;
    }

    public String getAdvert_url() {
        return advert_url;
    }

    public void setAdvert_url(String advert_url) {
        this.advert_url = advert_url;
    }

}
