package com.test4s.gdb;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.test4s.gdb.IndexItemInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table INDEX_ITEM_INFO.
*/
public class IndexItemInfoDao extends AbstractDao<IndexItemInfo, Long> {

    public static final String TABLENAME = "INDEX_ITEM_INFO";

    /**
     * Properties of entity IndexItemInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, String.class, "user_id", false, "USER_ID");
        public final static Property Logo = new Property(2, String.class, "logo", false, "LOGO");
        public final static Property Identity_cat = new Property(3, String.class, "identity_cat", false, "IDENTITY_CAT");
        public final static Property Company_name = new Property(4, String.class, "company_name", false, "COMPANY_NAME");
        public final static Property Method_name = new Property(5, String.class, "method_name", false, "METHOD_NAME");
    };


    public IndexItemInfoDao(DaoConfig config) {
        super(config);
    }
    
    public IndexItemInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'INDEX_ITEM_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'USER_ID' TEXT," + // 1: user_id
                "'LOGO' TEXT," + // 2: logo
                "'IDENTITY_CAT' TEXT," + // 3: identity_cat
                "'COMPANY_NAME' TEXT," + // 4: company_name
                "'METHOD_NAME' TEXT);"); // 5: method_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'INDEX_ITEM_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, IndexItemInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(3, logo);
        }
 
        String identity_cat = entity.getIdentity_cat();
        if (identity_cat != null) {
            stmt.bindString(4, identity_cat);
        }
 
        String company_name = entity.getCompany_name();
        if (company_name != null) {
            stmt.bindString(5, company_name);
        }
 
        String method_name = entity.getMethod_name();
        if (method_name != null) {
            stmt.bindString(6, method_name);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public IndexItemInfo readEntity(Cursor cursor, int offset) {
        IndexItemInfo entity = new IndexItemInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // logo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // identity_cat
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // company_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // method_name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, IndexItemInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLogo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdentity_cat(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCompany_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMethod_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(IndexItemInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(IndexItemInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
