package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INDEX_ITEM_INFO.
 */
public class IndexItemInfo {

    private Long id;
    private String user_id;
    private String logo;
    private String identity_cat;
    private String company_name;
    private String method_name;

    public IndexItemInfo() {
    }

    public IndexItemInfo(Long id) {
        this.id = id;
    }

    public IndexItemInfo(Long id, String user_id, String logo, String identity_cat, String company_name, String method_name) {
        this.id = id;
        this.user_id = user_id;
        this.logo = logo;
        this.identity_cat = identity_cat;
        this.company_name = company_name;
        this.method_name = method_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getIdentity_cat() {
        return identity_cat;
    }

    public void setIdentity_cat(String identity_cat) {
        this.identity_cat = identity_cat;
    }

    public String getCompany_name() {
        return company_name;
    }

    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    public String getMethod_name() {
        return method_name;
    }

    public void setMethod_name(String method_name) {
        this.method_name = method_name;
    }

}
