package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INFORMATION.
 */
public class Information {

    private Long id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String time;
    private Integer looknum;
    private Integer comment_num;
    private String context;

    public Information() {
    }

    public Information(Long id) {
        this.id = id;
    }

    public Information(Long id, String title, String time, Integer looknum, Integer comment_num, String context) {
        this.id = id;
        this.title = title;
        this.time = time;
        this.looknum = looknum;
        this.comment_num = comment_num;
        this.context = context;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public Integer getLooknum() {
        return looknum;
    }

    public void setLooknum(Integer looknum) {
        this.looknum = looknum;
    }

    public Integer getComment_num() {
        return comment_num;
    }

    public void setComment_num(Integer comment_num) {
        this.comment_num = comment_num;
    }

    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

}
