package com.test4s.gdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IP.
 */
public class IP {

    private String company_name;
    private String id;
    private String ip_name;
    private String ip_logo;
    private String ip_style;
    private String ip_cat;
    private String uthority;
    private String type;
    private String style;
    private String range;
    private String introuduction;
    private String location;
    private String scale;
    private String webSite;
    private String telePhone;
    private String address;
    private String otherIp;

    public IP() {
    }

    public IP(String company_name, String id, String ip_name, String ip_logo, String ip_style, String ip_cat, String uthority, String type, String style, String range, String introuduction, String location, String scale, String webSite, String telePhone, String address, String otherIp) {
        this.company_name = company_name;
        this.id = id;
        this.ip_name = ip_name;
        this.ip_logo = ip_logo;
        this.ip_style = ip_style;
        this.ip_cat = ip_cat;
        this.uthority = uthority;
        this.type = type;
        this.style = style;
        this.range = range;
        this.introuduction = introuduction;
        this.location = location;
        this.scale = scale;
        this.webSite = webSite;
        this.telePhone = telePhone;
        this.address = address;
        this.otherIp = otherIp;
    }

    public String getCompany_name() {
        return company_name;
    }

    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIp_name() {
        return ip_name;
    }

    public void setIp_name(String ip_name) {
        this.ip_name = ip_name;
    }

    public String getIp_logo() {
        return ip_logo;
    }

    public void setIp_logo(String ip_logo) {
        this.ip_logo = ip_logo;
    }

    public String getIp_style() {
        return ip_style;
    }

    public void setIp_style(String ip_style) {
        this.ip_style = ip_style;
    }

    public String getIp_cat() {
        return ip_cat;
    }

    public void setIp_cat(String ip_cat) {
        this.ip_cat = ip_cat;
    }

    public String getUthority() {
        return uthority;
    }

    public void setUthority(String uthority) {
        this.uthority = uthority;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public String getRange() {
        return range;
    }

    public void setRange(String range) {
        this.range = range;
    }

    public String getIntrouduction() {
        return introuduction;
    }

    public void setIntrouduction(String introuduction) {
        this.introuduction = introuduction;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getScale() {
        return scale;
    }

    public void setScale(String scale) {
        this.scale = scale;
    }

    public String getWebSite() {
        return webSite;
    }

    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    public String getTelePhone() {
        return telePhone;
    }

    public void setTelePhone(String telePhone) {
        this.telePhone = telePhone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getOtherIp() {
        return otherIp;
    }

    public void setOtherIp(String otherIp) {
        this.otherIp = otherIp;
    }

}
